"""Render a static gallery of example reports into docs/examples/.

Lets a visitor see real generated artifacts (risk assessment, AI-security lens,
STRIDE, red-team plan, control catalogue, data-security, FRIA, compliance tracker)
straight on GitHub, without running the app. Reproducible: deterministic content
with a fixed timestamp, so re-running only changes files whose content changed.

    python scripts/build_gallery.py
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app import reports  # noqa: E402
from app.classifier import classify  # noqa: E402

OUT = ROOT / "docs" / "examples"
FIXED_TS = "2026-06-17T00:00:00+00:00"

# Curated: (example file, one-line note, [report types]).
GALLERY = [
    ("grid_ops_agent.json",
     "Annex III-2 critical-infrastructure agent — High risk *and* a Critical "
     "AI-security profile. The architecture-aware depth showcase.",
     ["risk", "security", "stride", "redteam", "controls"]),
    ("hiring_cv_screening.json",
     "CV-screening (Annex III-4 employment) — the high-risk governance pack.",
     ["risk", "fria", "compliance", "techdoc"]),
    ("foundation_model.json",
     "A general-purpose AI model (GPAI, Chapter V) — the data-security lens.",
     ["risk", "datasec", "modelcard"]),
    ("support_chatbot.json",
     "Public RAG helpbot — the offense↔defense loop (red-team test ↔ control).",
     ["security", "redteam", "controls", "datasec"]),
    ("social_scoring.json",
     "A prohibited practice (Art. 5) — what a banned system looks like.",
     ["risk"]),
]

TYPE_LABEL = {
    "risk": "Risk assessment", "security": "AI security lens",
    "stride": "STRIDE threat model", "redteam": "Red-team test plan",
    "controls": "Control catalogue", "datasec": "Data security (DSGAI)",
    "fria": "FRIA (Art. 27)", "compliance": "Compliance tracker",
    "techdoc": "Annex IV technical docs", "modelcard": "Model card",
}


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    index = ["# Example report gallery\n",
             "Real artifacts generated by the deterministic engine for the "
             "synthetic example systems — no setup required. Regenerate with "
             "`python scripts/build_gallery.py`. Try them live in the "
             "[demo](https://huggingface.co/spaces/JesseKasteele/ai-act-companion).\n"]
    written = 0
    for fname, note, types in GALLERY:
        answers = {k: v for k, v in json.loads((ROOT / "examples" / fname).read_text(
            encoding="utf-8")).items() if not k.startswith("_")}
        cls = classify(answers)
        slug = fname.replace(".json", "").replace("_", "-")
        assessment = {"id": slug, "created_at": FIXED_TS,
                      "answers": answers, "classification": cls}
        index.append(f"\n## {answers['sys_name']} — {cls['tier_label']}\n")
        index.append(f"{note}\n\n")
        for rtype in types:
            _t, _fn, md = reports.render(rtype, assessment)
            path = OUT / f"{slug}-{rtype}.md"
            path.write_text(md, encoding="utf-8")
            index.append(f"- [{TYPE_LABEL.get(rtype, rtype)}]({path.name})\n")
            written += 1
    (OUT / "README.md").write_text("".join(index), encoding="utf-8")
    print(f"  wrote {written} report files + README.md into {OUT}")


if __name__ == "__main__":
    main()
